Repository bitburner-official/bitburner-src, pull requests merged in 2023-08, with the labels that each got.

#706 API: wrote singularity.getAugmentationFactions
  markdown/bitburner.singularity.getaugmentationfactions.md
  markdown/bitburner.singularity.md
  src/Netscript/RamCostGenerator.ts
  src/NetscriptFunctions/Singularity.ts
  src/ScriptEditor/NetscriptDefinitions.d.ts
Labels: enhancement

#702 MISC: Remove all remaining readthedocs references
  README.md
  doc/CONTRIBUTING.md
  src/Documentation/doc/advanced/corporations.md
  src/Documentation/doc/changelog.md
  src/GameOptions/ui/GameOptionsSidebar.tsx
  src/GameOptions/ui/RemoteAPIPage.tsx
  src/Literature/Literatures.ts
  src/PersonObjects/Sleeve/ui/SleeveRoot.tsx
  src/ScriptEditor/NetscriptDefinitions.d.ts
  src/ScriptEditor/ui/Toolbar.tsx
  src/StockMarket/ui/InfoAndPurchases.tsx
Labels: documentation

#494 UI: Move pagination to top of active scripts, improve filtering
  src/ui/ActiveScripts/ServerAccordionContent.tsx
  src/ui/ActiveScripts/ServerAccordions.tsx
Labels: UI bug
